import { useEffect, useState } from 'react';
import { Calendar, Edit3, Loader2, Plus, Radio } from 'lucide-react';
import Modal from '../../../components/Modal';
import { academyAPI } from '../../../lib/academy';
import { useToast } from '../../../lib/toast';

interface Live { id: string; title: string; description: string | null; session_date: string | null; video_provider: string | null; video_external_id: string | null; video_url: string | null; duration_seconds: number | null; status: string; access_mode: string }
type LiveForm = { title: string; description: string; session_date: string; video_provider: string; video_external_id: string; video_url: string; duration_minutes: string; status: string; access_mode: string };
const emptyForm: LiveForm = { title: '', description: '', session_date: '', video_provider: 'youtube', video_external_id: '', video_url: '', duration_minutes: '', status: 'draft', access_mode: 'free_registered' };

export default function AdminLives() {
  const toast = useToast();
  const [lives, setLives] = useState<Live[]>([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Live | null>(null);
  const [form, setForm] = useState<LiveForm>(emptyForm);
  const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); try { setLives(await academyAPI.getAdminLives() as Live[]); } catch { toast.error('No se pudieron cargar las lives.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function edit(live: Live | null) { setEditing(live); setForm(live ? { title: live.title, description: live.description ?? '', session_date: live.session_date ? live.session_date.slice(0, 16) : '', video_provider: live.video_provider ?? 'youtube', video_external_id: live.video_external_id ?? '', video_url: live.video_url ?? '', duration_minutes: live.duration_seconds ? String(Math.round(live.duration_seconds / 60)) : '', status: live.status, access_mode: live.access_mode } : emptyForm); setOpen(true); }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { const live = await academyAPI.saveAdminLive(editing?.id ?? null, { title: form.title, description: form.description, session_date: form.session_date ? new Date(form.session_date).toISOString() : null, video_provider: form.video_provider || null, video_external_id: form.video_external_id || null, video_url: form.video_url || null, duration_seconds: form.duration_minutes ? Number(form.duration_minutes) * 60 : null, status: form.status, access_mode: form.access_mode }); setLives((current) => editing ? current.map((item) => item.id === editing.id ? live as Live : item) : [live as Live, ...current]); setOpen(false); toast.success(editing ? 'Live actualizada.' : 'Live creada.'); } catch { toast.error('No se pudo guardar la live.'); } finally { setSaving(false); } }
  return <div className="space-y-6"><div className="flex items-center justify-between gap-4"><div><h1 className="text-2xl font-black text-[#111111]">Lives Academy</h1><p className="text-[#6B7280]">Administra sesiones y grabaciones publicadas.</p></div><button type="button" onClick={() => edit(null)} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#1A4E26] text-white font-bold"><Plus size={18} /> Nueva live</button></div>{loading ? <div className="py-16 text-center text-[#6B7280]"><Loader2 className="animate-spin inline mr-2" size={20} /> Cargando...</div> : <div className="bg-white border border-[#C8D8CB] rounded-2xl overflow-hidden divide-y divide-[#E5ECE6]">{lives.length === 0 ? <p className="p-12 text-center text-[#6B7280]">No hay sesiones creadas.</p> : lives.map((live) => <div key={live.id} className="p-5 flex items-center gap-4"><div className="h-11 w-11 rounded-xl bg-[#EBF4ED] text-[#1A4E26] flex items-center justify-center"><Radio size={21} /></div><div className="flex-1 min-w-0"><h2 className="font-bold truncate">{live.title}</h2><p className="text-xs text-[#6B7280] mt-1">{live.status} · {live.video_provider || 'sin video'}{live.session_date ? ` · ${new Date(live.session_date).toLocaleDateString('es-EC')}` : ''}</p></div><button type="button" onClick={() => edit(live)} aria-label={`Editar ${live.title}`} className="p-2 rounded-lg text-[#1A4E26] hover:bg-[#EBF4ED]"><Edit3 size={17} /></button></div>)}</div>}
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Editar live' : 'Nueva live'} subtitle="Configura la sesión y su acceso." size="lg"><form onSubmit={save} className="p-6 space-y-4"><Field label="Título" value={form.title} onChange={(value) => setForm((current) => ({ ...current, title: value }))} required /><label className="block text-sm font-semibold">Descripción<textarea value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} rows={3} className="mt-1 w-full px-3 py-2 border border-slate-200 rounded-xl" /></label><div className="grid sm:grid-cols-2 gap-3"><Field label="Fecha y hora" value={form.session_date} onChange={(value) => setForm((current) => ({ ...current, session_date: value }))} type="datetime-local" /><Field label="Duración (minutos)" value={form.duration_minutes} onChange={(value) => setForm((current) => ({ ...current, duration_minutes: value }))} type="number" min="0" /></div><div className="grid sm:grid-cols-2 gap-3"><Select label="Proveedor" value={form.video_provider} onChange={(value) => setForm((current) => ({ ...current, video_provider: value }))} options={['youtube', 'vimeo', 'custom']} /><Field label="ID externo" value={form.video_external_id} onChange={(value) => setForm((current) => ({ ...current, video_external_id: value }))} /></div><Field label="URL alternativa" value={form.video_url} onChange={(value) => setForm((current) => ({ ...current, video_url: value }))} /><div className="grid sm:grid-cols-2 gap-3"><Select label="Estado" value={form.status} onChange={(value) => setForm((current) => ({ ...current, status: value }))} options={['draft', 'published', 'archived']} /><Select label="Acceso" value={form.access_mode} onChange={(value) => setForm((current) => ({ ...current, access_mode: value }))} options={['public', 'free_registered', 'sumak_exclusive', 'assigned', 'hidden']} /></div><div className="flex justify-end gap-3 pt-3 border-t border-[#E5ECE6]"><button type="button" onClick={() => setOpen(false)} className="px-4 py-2 text-sm font-bold text-[#6B7280]">Cancelar</button><button type="submit" disabled={saving} className="px-4 py-2 rounded-xl bg-[#1A4E26] text-white font-bold text-sm">{saving ? 'Guardando...' : 'Guardar live'}</button></div></form></Modal></div>;
}
function Field({ label, value, onChange, type = 'text', min, required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; min?: string; required?: boolean }) { return <label className="block text-sm font-semibold text-[#111111]">{label}<input required={required} type={type} min={min} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full px-3 py-2 border border-slate-200 rounded-xl" /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="block text-sm font-semibold text-[#111111]">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full px-3 py-2 border border-slate-200 rounded-xl bg-white">{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }